---
- name: Set HTTP proxy for subscription-manager (RHSM)
  ini_file:
    path: /etc/rhsm/rhsm.conf
    section: server
    option: proxy_hostname
    value: "{{ set_proxy4rhsm_proxy_hostname  }}"
    backup: yes
  become: yes

- name: Set proxy port for subscription-manager (RHSM)
  ini_file:
    path: /etc/rhsm/rhsm.conf
    section: server
    option: proxy_port
    value: "{{ set_proxy4rhsm_proxy_port  }}"
    backup: yes
  become: yes
